// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBje49IRywcoQegAqibKey6I_dSR8CziTM',
    appId: '1:896402852323:web:39a0b2c074ba0de30d78d6',
    messagingSenderId: '896402852323',
    projectId: 'sms-api-759b4',
    authDomain: 'sms-api-759b4.firebaseapp.com',
    storageBucket: 'sms-api-759b4.firebasestorage.app',
    measurementId: 'G-2P47Q34SL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7XEG_pkcI43-7L-WnyQpKx2H1aIWFkWU',
    appId: '1:896402852323:android:8f655785731224020d78d6',
    messagingSenderId: '896402852323',
    projectId: 'sms-api-759b4',
    storageBucket: 'sms-api-759b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmQG3S3vcXuwBihhcqhIxWRcs4K08ggDM',
    appId: '1:896402852323:ios:f48ac2cdaf8a86e90d78d6',
    messagingSenderId: '896402852323',
    projectId: 'sms-api-759b4',
    storageBucket: 'sms-api-759b4.firebasestorage.app',
    iosBundleId: 'com.example.smsMobileApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmQG3S3vcXuwBihhcqhIxWRcs4K08ggDM',
    appId: '1:896402852323:ios:f48ac2cdaf8a86e90d78d6',
    messagingSenderId: '896402852323',
    projectId: 'sms-api-759b4',
    storageBucket: 'sms-api-759b4.firebasestorage.app',
    iosBundleId: 'com.example.smsMobileApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBje49IRywcoQegAqibKey6I_dSR8CziTM',
    appId: '1:896402852323:web:1253ee6e07795ce80d78d6',
    messagingSenderId: '896402852323',
    projectId: 'sms-api-759b4',
    authDomain: 'sms-api-759b4.firebaseapp.com',
    storageBucket: 'sms-api-759b4.firebasestorage.app',
    measurementId: 'G-LYE3B94YD2',
  );
}
